#!/bin/sh

set -e

lb config noauto \
   --mirror-bootstrap http://deb.debian.org/debian/ \
   --mirror-binary http://deb.debian.org/debian/ \
   --security false \
   --updates false \
   --distribution bookworm \
   --debian-installer live \
   --debian-installer-distribution bookworm \
   --cache-packages false \
   --archive-areas "main non-free-firmware" \
   --iso-volume 'autoruns' \
   --image-name 'autoruns' \
   --bootappend-live 'boot=live components quiet splash findiso=${iso_path} nouveau.blacklist=1' \
   --bootappend-live-failsafe 'boot=live components memtest noapic noapm nodma nomce nolapic nosmp nosplash vga=788 nouveau.blacklist=1' \
   --uefi-secure-boot enable \
   --source true \
   "${@}"
